-- begin PETCLINIC_VISIT
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ASSIGNED_NURSE foreign key (ASSIGNED_NURSE_ID) references SEC_USER(ID)^
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_PET foreign key (PET_ID) references PETCLINIC_PET(ID)^
create index IDX_PETCLINIC_VISIT_ASSIGNED_NURSE on PETCLINIC_VISIT (ASSIGNED_NURSE_ID)^
create index IDX_PETCLINIC_VISIT_PET on PETCLINIC_VISIT (PET_ID)^
-- end PETCLINIC_VISIT
-- begin PETCLINIC_PET
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_TYPE foreign key (TYPE_ID) references PETCLINIC_PET_TYPE(ID)^
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID)^
create unique index IDX_PETCLINIC_PET_ID_UNQ on PETCLINIC_PET (IDENTIFICATION_NUMBER, DELETE_TS) where DELETE_TS is null ^
create index IDX_PETCLINIC_PET_TYPE on PETCLINIC_PET (TYPE_ID)^
create index IDX_PETCLINIC_PET_OWNER on PETCLINIC_PET (OWNER_ID)^
-- end PETCLINIC_PET
-- begin PETCLINIC_VETERINARIAN_SPECIALTY_LINK
alter table PETCLINIC_VETERINARIAN_SPECIALTY_LINK add constraint FK_VETSPE_VETERINARIAN foreign key (VET_ID) references PETCLINIC_VETERINARIAN(ID)^
alter table PETCLINIC_VETERINARIAN_SPECIALTY_LINK add constraint FK_VETSPE_SPECIALTY foreign key (SPECIALTY_ID) references PETCLINIC_SPECIALTY(ID)^
-- end PETCLINIC_VETERINARIAN_SPECIALTY_LINK
